spring.datasource.url=jdbc:postgresql://localhost:5432/interviewos
spring.datasource.username=postgres
spring.datasource.password=fahim321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ThisIsASecretKeyForInterviewOSProject123456789012345
jwt.expiration-ms=86400000

leetcode.api-url=https://leetcode.com/graphql